### ISSUE TITLE
update header and accent color codes

### ISSUE THREAD

**Issue by PathfinderCTO** [404pandas/momentum-blog#1]
Please update blog color to a lighter shade like 
![image](https://github.com/404pandas/momentum-blog/assets/141790383/5b065b93-c5a6-4d39-bcf8-25981ebc932a)

**Comment by PathfinderCTO** [comment]
updated the green color right in the ghost settings. It looks like the styling of the green subscribe button within the header is controlled somewhere else. @404pandas Can you change it also to #a9a962 ? Apricot code updated on vars.css which is waiting on a PR.

**Comment by 404pandas** [comment]
![Screenshot 2024-07-03 at 11 06 11 PM](https://github.com/404pandas/momentum-blog/assets/113853550/d285dcb7-72ee-41b2-af86-d02cb294851c)

**Comment by 404pandas** [comment]
This mistakenly got closed when I was trying to link the branch/pr with the issue. Apologies!
